### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by jeongtae**
Hello!

I translated the app into Korean.
I worked with a tone similar to native macOS as much as possible.

However, the app was not built well in my local development environment, so I couldn't actually check the results.
Please let me know if there are any necessary changes.

Thank you for making such a great app!

### CODE REVIEW

**Comment by noah-nuebling** [comment]
Hi @jeongtae, thanks so much for your contribution! I'm really happy that you care enough about the project and about making it better to put in the time and effort to make a translation. And I'm also happy that the app is going to be better for Korean users. So thank you!
I also showed your work to my Korean friend and she said you did a really good job! :)

I found some minor things that might be improved:
1. In some places the markdown highlights don't work and instead you see underscores (`_`). Example: 
    Screenshot 2023-01-29 at 23 14 32
    This seems to happen because Korean sometimes doesn't have space characters between the highlighted words. To fix this, you can replace the underscore charcters (`_`) with stars (`*`). I don't know why this works, but it does. I can also fix this myself - but I'll only have time to focus on that after 3.0.0 is released.

2. The scroll tab layout is very wide
    CleanShot 2023-01-28 at 03 50 24@2x
    The scroll tab layout grows its width to fit the UI text. I think it looks a little weird if it gets really wide. So in German and English I put linebreaks (`\n`) into the UI text so the layout doesn't become as wide.
    Screenshot 2023-01-29 at 23 08 53
    This is just a suggestion. It's a matter of taste so I'll leave it up to you how or if you want to do this.

3. Using English "Milkshake"
    CleanShot 2023-01-28 at 03 51 03@2x
    I noticed you use the English letters for macOS features and for Mac Mouse Fix which totally makes sense to me and which is in line with other macOS apps by Apple. Is there a reason you also used the English letters for 'Milkshake'? Using 'Milkshake' makes the width of that link a little wide compared to the other links which use mostly Korean letters. Again, just something I noticed. You definitely have the creative difection here, as a Korean speaker.

4. The Menu Bar isn't translated to Korean
   CleanShot 2023-01-28 at 03 45 54@2x
   You can find the translation file at `Mouse Fix Project > Helper > UI > MenuBarItem > MenuBarItem.strings (Korean)`

To test your translations, I created a new branch [`jeongtae-korean-translation`](https://github.com/noah-nuebling/mac-mouse-fix/tree/jeongtae-korean-translation) where I fixed some of the visual layouts so they don't break with the narrow Korean text. 
So if you want to keep working on the translations and test them on your own machine, it's probably best if you make your improvements based on the `jeongtae-korean-translation` branch, or if you merge that branch into your pull request or something. (Don't have too much experience working with pull requests, so let me know if you know of a better way to handle this)

If I can help you in some way to get the app to compile on your machine let me know! I think that's probably the most efficient way for you to work on the translations and immediately check the results.

Let me know if you have any more questions and thanks so much again!

**Comment by jeongtae** [comment]
Thank you for the detailed review.
I haven't used Xcode a lot, so I didn't know how to compile it properly. So I did some googling, and now I can compile and run it.
So I was able to improve all the issues you mentioned one by one while looking at the actual app screen.

And these are the details of the commits.

1. Merged `version-3` branch and `jeongtae-korean-translation` branch into this branch.

2. Replaced all underscore characters with asterisks and now it works nicely.

    [commit `d16943e`](https://github.com/noah-nuebling/mac-mouse-fix/pull/499/commits/d16943e9fcdfab6f0e86bf2d0233d68ded0d9290)

    image

3. Put some new line characters to make the Scrolling tab have a proper width.

    [commit `787a1f0`](https://github.com/noah-nuebling/mac-mouse-fix/pull/499/commits/787a1f0e094975905595b3a42190dc8c6eebbff5)

    스크린샷 2023-01-31 오후 10 51 31

4. Reduced length of the translation text corresponding to 'Buy Me a Milkshake :)'.

    As a result, the width of the Information tab has been reduced properly.

    Instead, the object word 'Me' was omitted. This is natural in Korean, and I think it is not unreasonable to convey the meaning.

    [commit `44f7f1e`](https://github.com/noah-nuebling/mac-mouse-fix/pull/499/commits/44f7f1e00a99812b4bf4ef2cc1dd3ed8127ec448)

    스크린샷 2023-01-31 오후 11 09 14

5. Translated MenuBarItem 

    [commit `3655d20`](https://github.com/noah-nuebling/mac-mouse-fix/pull/499/commits/3655d20395ee170011f1e6df49e13facc56231de)

    image

6. Improved some Korean translation

    [commit `6ebff84`](https://github.com/noah-nuebling/mac-mouse-fix/pull/499/commits/6ebff84b76d656e8bfb2f587242e3026ae5b4047)

**Comment by noah-nuebling** [comment]
Thanks for getting back so quick. Everything's looking great and I just accepted your pull request!

Thanks so much again for your awesome contribution!

**Comment by noah-nuebling** [comment]
If you shoot me an email at noah . n . public @ gmail . com I'll send you 10 free licenses

**Pull request merged**
