### PR TITLE
added minor translation

### PR DESCRIPTION
**Pull request by nghlt**

### CODE REVIEW

**Comment by noah-nuebling** [comment]
Hey @nghlt, that’s looking good. But on this page (https://support.apple.com/vi-vn/102482) they don’t translate “Mission Control”, is there a reason you translated it here?

**Comment by nghlt** [comment]
That term can be clearly translated to Vietnamese. However, with the references, I think I should use the one in Apple's guideline. I reversed the translation and push it back to the PR.

**Comment by nghlt** [comment]
Additionally, I change `sơ cấp` and `thứ cấp` to `chính` and `phụ`, respectively, to shorten the text and make the UI concise

**Comment by noah-nuebling** [comment]
Great that sounds like a good change!

I just ran the app it looks great so far, but I found 2 small spots in the UI that should maybe be translated still:

'Click and Drag' and 'Trackball Mice' in this screen should maybe be translated:

Screenshot 2024-01-12 at 02 20 07

In this screen, 'Mouse > Scrolling Speed' should probably be translated:
Screenshot 2024-01-12 at 02 22 36

Other than that, it looks great to me! The 'State of Localization' also shows no more problems for Vietnamese now.

If you wanna fix that stuff you can create another pull request.

Thanks again for all your work!

**Comment by noah-nuebling** [comment]
I found another small potential issue:

This text should probably have a `.` at the end:

Screenshot 2024-01-12 at 04 30 35

**Comment by noah-nuebling** [comment]
Hey there @nghlt, 

I'm planning to release a 3.0.1 update featuring your Vietnamese translations.

If you'd like to make any more changes to the Vietnamese translations before the update, let me know, otherwise I'll release your translations as they are. You can still make changes at any later point if you like.

I can also pay you or something? I don't know how much work this is or if any of this is overwhelming or if I'm hard to work with or anything. So if you have any feedback on the process of all this, let me know.

If you do wanna be compensated, what do you think a fair price would be?

I realize I could've given you the feedback from the last 2 comments before merging the commit, so I hope that wasn't too annoying or something.

Ok, hope that works, and let me know if you have any more questions.

Here's the current draft of the 3.0.1 release notes:

CleanShot 2024-01-15 at 04 47 03@2x

**Comment by nghlt** [comment]
I'm sorry for late reply. I added a new PR. Hope it's helpful for the new release.

**Pull request merged**
