### PR TITLE
update 🌏 State of Localization 🌎 states

### PR DESCRIPTION
**Pull request by nghlt**
I checked and updated the translation.

### CODE REVIEW

**Comment by noah-nuebling** [comment]
Great! Thank you for your work. It looks almost good as far as I can tell but should `Thật là mượt màààààààà` have that many a's? It's just the label for the 'Smoothness' setting on the 'Scrolling' tab.

**Comment by noah-nuebling** [comment]
Also small issue: in `"trigger.scroll-particle" = "Cuộn";`, the `Cuộn` should not be capitalized so it exactly matches the `cuộn` in trigger strings like `Kích và cuộn %@`. 

Same goes for `"trigger.drag-particle" = "Kéo";`. 

I think this was easy to overlook, so I updated the localizor hints to make it clearer - which lead to a merge conflict. Let me know in case you need any help with that.

**Comment by nghlt** [comment]
> Great! Thank you for your work. It looks almost good as far as I can tell but should `Thật là mượt màààààààà` have that many a's? It's just the label for the 'Smoothness' setting on the 'Scrolling' tab.

Sorry for that, I missed it.

> the `Cuộn` should not be capitalized so it exactly matches the cuộn in trigger strings like `Kích và cuộn %@`

I added the modification. Just a small question, why do you capitalize the "S" in `First draft: Scroll` and `"trigger.scroll-particle" = "Scroll";`

**Comment by noah-nuebling** [comment]
> Sorry for that, I missed it.

No problem! Happens to anyone.

> Just a small question, why do you capitalize the "S"

Good question! In English the string where we want to emphasize the `Drag` is `Double Click and Drag %@`. And in that string, the `Drag` is capitalized, because it's using [title case](https://titlecaseconverter.com/).

I totally get how this can be confusing, though, so I updated the hints to hopefully make it clearer.

**Comment by noah-nuebling** [comment]
Is there anything else you want to add? Otherwise I'd merge your translations!

**Comment by nghlt** [comment]
That’s all. Waiting to the next update 😊

**Comment by noah-nuebling** [comment]
Nice!

Thanks again for your contribution to Mac Mouse Fix. :)

**Comment by noah-nuebling** [comment]
Hey @nghlt, there are three unchanged translations still showing up in the State of Localization:

"apple-key-fallback.capslock" = "⇪";
"effect.mission-control" = "Mission Control";
"scroll-effect.rotate" = "Rotate";

If you file one more pull request updating these, then your Vietnamese localization should be ready to go.

**Comment by noah-nuebling** [comment]
I just added a mention of your contributions to the [Acknowledgements](https://github.com/noah-nuebling/mac-mouse-fix/blob/master/Acknowledgements.md)!

If you would like to get a bunch of free MMF licenses, just email me. If there's anything other stuff you'd like to see as a 'reward' for translating MMF, let me know. I can't really think of anything cool.

**Comment by nghlt** [comment]
I added a minor update and created a pull request. Hope to make it perfect

**Pull request merged**
