### PR TITLE
add 🇻🇳 Vietnamese

### PR DESCRIPTION
**Pull request by nghlt**

### CODE REVIEW

**Comment by noah-nuebling** [comment]
Hi there @nghlt. Thank you so much for your pull request! 

I'm excited to add Vietnamese to the list of languages that Mac Mouse Fix supports!

I found some strings that are not yet translated. Such as `mail-alert.send" = "Write Email";` at `Localization/vi.lproj/Localizable.strings`. 

If you want to translate them, you can update this pull request. Otherwise I can also merge this and perhaps others can fill in the missing translations later.

Thank you for your work.

**Comment by nghlt** [comment]
Hi,
I added some modifies. Others could be updated if needed.

**Comment by noah-nuebling** [comment]
Hey @nghlt, thank you very much for your updates! I want to integrate them into MMF soon, but I'm currently working on a system that automatically checks translations for any issues, I want to figure that out first and then I'll give you updates here. Thank you very much for your work though!

**Comment by noah-nuebling** [comment]
Hey there @nghlt, I finished the new Localization System now!!

You can look at the "State of Localization" comment on this [discussion](https://github.com/noah-nuebling/mac-mouse-fix/discussions/731) to see any potential problems with your localization that the Localization System has detected.

It looks mostly fine, except for a few localizations missing.

If there's a translation that shows up in the "State of Localization" as potentially needing an update but you think that it is okay as it is, then you can mark the translation with an `// !IS_OK` comment. That way, it won't show up in the "State of Localization" as a problem anymore . See "Note on !IS_OK flag" in the [discussion](https://github.com/noah-nuebling/mac-mouse-fix/discussions/731) for an example and more info.

Ok that's it. It would be great if you could file another pull request with updates based on the "State of Localization" comment, and then your Vietnamese Localization should be good to go!

If you have any more questions, let me know.

**Comment by noah-nuebling** [comment]
Oh and if you have any feedback on the experience of translating MMF - if it's confusing or difficult or something doesn't makes sense or anything like that - please do let me know! I want to make the experience as nice and non-intimidating as possible. (Which I realise is probably not that easy given that you have to know some git and edit code files and all that)

**Pull request merged**
