### PR TITLE
Feature/inverted side buttons

### LINKED ISSUE #27: Invert side buttons
For some reason the side buttons on my mouse are detected in an inverted order, making the back button trigger the forward action and vice versa. Would you consider adding an option to invert the side buttons?

### PR DESCRIPTION
**Pull request by divadretlaw**
Add `sideButtonInverted` to `ButtonRemaps`
Add a checkbox to invert the side buttons

if the checkbox is checked it simply adds the selected side button config in reverse order

Closes #27 #56

### CODE REVIEW

**Comment by AndriyBalakalchuk** [comment]
Please merge all to work file I very want to replace my -official version on this - to have a possibility to swap side mouse buttons --- David, thanks a lot for your work!!!!

**Comment by matthewgregg** [comment]
> Please merge all to work file I very want to replace my -official version on this - to have a possibility to swap side mouse buttons --- David, thanks a lot for your work!!!!

The attached version has this pr merged. I also built it as a universal binary but I don't have an Apple Silicon Mac to test on

[Mouse Fix.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/5934536/Mouse.Fix.zip)

**Comment by AndriyBalakalchuk** [comment]
Ooooh!! Thank you, Matthew, and thanks to all community - after all at my mac mini 2018 (intel core i5) all works as I imagined! - super cool work! and I really expect that the script patch will be integrated into the main version by the first author :)
Thanks once more - guys, you did my life better, and I really believe this is one that was really the target of human lives -- do good for each other ♥︎

**Comment by matthewgregg** [comment]
You're welcome!

**Comment by noah-nuebling** [comment]
Hey guys thanks so much for getting involved! That's So cool. Nice work @divadretlaw :)

I merged this feature for the new [1.0 release](https://mousefix.org).

**Pull request merged**
