### PR TITLE
Localisation for Chinese

### PR DESCRIPTION
**Pull request by groverlynn**

### CODE REVIEW

**Comment by groverlynn** [comment]
Sorry for opening another pull. I reorganized branches in my fork, which closed #385

**Comment by noah-nuebling** [comment]
Hey @groverlynn, no worries at all! Thanks again for all your effort!

I've now published [Beta 4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-4) and it contains all the UI additions and changes that I was still planning on.

So I think that that the UI is now finally "stable" and I won't change any more stuff that you've already translated unless it's absolutely necessary.

I'll be happy to merge your translations for Beta 5!

**Comment by groverlynn** [comment]
This should now cover everything up to beta 4

**Comment by noah-nuebling** [comment]
Hey @groverlynn! 

I added one new new UI string with the key ~~`is-strange-helper-toast`~~ `is-strange-helper-alert.title` and `is-strange-helper-alert.body` in 3.0.0 Beta 5.
I also very slightly changed the English UI strings with the key `is-disabled-toast` and `9qp-gN-SZZ.title`. Don't think it's necessary for you to update them.

Will probably merge your translations for Beta 6. I didn't merge for Beta 5 since many people had scrolling issues so I wanted to push the update sooner.

Thanks for your great work!

**Comment by noah-nuebling** [comment]
By the way how did you find out which UI Strings were added or changed before?

**Comment by groverlynn** [comment]
@noah-nuebling  All updated now up to beta 5

> By the way how did you find out which UI Strings were added or changed before?

I just go through the commits to see whether the localization strings files have been modified.

**Comment by groverlynn** [comment]
Translation updated up to Beta 6

**Comment by noah-nuebling** [comment]
Hey @groverlynn, at long last I've now finally merged your translations! They are looking great! Thanks again for your hard work.

**Comment by noah-nuebling** [comment]
If you shoot me an email at noah . n . public @ gmail . com I'll send you  a bunch of free license keys

**Pull request merged**
